# Generated by Django 6.0.5 on 2026-06-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('email_subject', models.CharField(max_length=200)),
                ('email_body', models.TextField(blank=True)),
                ('whatsapp_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_groups', models.ManyToManyField(blank=True, related_name='campaigns', to='core.group')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
