# Generated by Django 6.0.5 on 2026-06-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='pdf_attachment',
            field=models.FileField(blank=True, null=True, upload_to='campaign_pdfs/'),
        ),
    ]
