# Generated by Django 6.0.5 on 2026-06-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_campaign_dry_run_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='auatomatically_send_when_due',
            field=models.BooleanField(default=False),
        ),
    ]
