# Generated by Django 6.0.5 on 2026-06-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_campaign_auatomatically_send_when_due'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='auatomatically_send_when_due',
            new_name='automatically_send_when_due',
        ),
    ]
