# Generated by Django 6.0.5 on 2026-06-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_auatomatically_send_when_due_campaign_automatically_send_when_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='ai_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='ai_review_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='ai_suggested_groups',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='campaign',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
    ]
