# Generated by Django 6.0.5 on 2026-06-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_campaign_ai_generated_at_campaign_ai_review_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='ai_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
