# Generated by Django 6.0.5 on 2026-06-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_campaign_ai_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='email_length',
            field=models.CharField(default='short', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tone',
            field=models.CharField(default='professional', max_length=20),
        ),
    ]
