# Generated by Django 6.0.5 on 2026-06-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_campaign_email_length_campaign_tone'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='heyzine_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='pdf_cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='campaign_covers/'),
        ),
    ]
