# Generated by Django 6.0.5 on 2026-06-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_campaign_heyzine_url_campaign_pdf_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='email_body_zh',
            field=models.TextField(blank=True),
        ),
    ]
