# Generated by Django 6.0.5 on 2026-06-09 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_campaign_email_body_zh'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='campaign_attachments/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='campaign_attachment_covers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.campaign')),
            ],
        ),
    ]
