# Generated by Django 6.0.5 on 2026-06-09 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_campaignattachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='heyzine_url',
            new_name='cover_link_url',
        ),
    ]
