# Generated by Django 6.0.5 on 2026-06-09 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_heyzine_url_campaign_cover_link_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='pdf_cover_image',
            new_name='cover_image',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='pdf_attachment',
            new_name='primary_attachment',
        ),
    ]
