# Generated by Django 6.0.5 on 2026-06-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_pdf_cover_image_campaign_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignattachment',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='campaign_covers/'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status'], name='core_campai_status_36ec94_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['scheduled_send_time'], name='core_campai_schedul_6f2b19_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['created_at'], name='core_campai_created_210e72_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverylog',
            index=models.Index(fields=['campaign', 'channel', 'status'], name='core_delive_campaig_c58e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverylog',
            index=models.Index(fields=['status', 'sent_at'], name='core_delive_status_71396f_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverylog',
            index=models.Index(fields=['person', 'campaign'], name='core_delive_person__222f4a_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['email'], name='core_person_email_9161a8_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['whatsapp_number'], name='core_person_whatsap_36e3d2_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['is_active'], name='core_person_is_acti_d4fb28_idx'),
        ),
    ]
