# Generated by Django 6.0.5 on 2026-06-12 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_campaignattachment_cover_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ai_campaign_created', 'AI Campaign Created'), ('ai_draft_queued', 'AI Draft Queued'), ('test_email_sent', 'Test Email Sent'), ('dry_run_created', 'Dry Run Created'), ('real_send_requested', 'Real Send Requested'), ('failed_emails_retried', 'Failed Emails Retried'), ('ai_groups_accepted', 'AI Groups Accepted')], max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_action_logs', to='core.campaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='core_userac_user_id_079621_idx'), models.Index(fields=['campaign', 'created_at'], name='core_userac_campaig_b3575d_idx'), models.Index(fields=['action', 'created_at'], name='core_userac_action_ff2614_idx')],
            },
        ),
    ]
