# Generated by Django 6.0.5 on 2026-06-25 15:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_useractionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='subscription_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
