# Generated by Django 6.0.5 on 2026-06-25 15:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_person_subscription_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='subscription_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
