# Generated by Django 6.0.5 on 2026-06-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_person_address_person_age_person_church_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
