# Generated by Django 6.0.5 on 2026-06-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_person_emergency_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
