from django.urls import path

from .views import (
    campaign_dry_run,
    campaign_preview,
    campaign_recipients,
    health_check,
    send_campaign_test_email_view,
    campaign_confirm_send,
    campaign_send_real_emails,
    campaign_retry_failed_emails,
    campaign_schedule_status,
    dashboard,
    campaign_generate_ai_draft,
    campaign_accept_ai_groups,
    ai_campaign_create,
    delivery_logs,
    audit_logs,
    campaign_detail,
)

urlpatterns = [
    path(
        "", dashboard, name="dashboard"
    ),
    path(
        "health/",
        health_check,
        name="health_check",
    ),
    path(
        "campaigns/<int:campaign_id>/preview/",
        campaign_preview,
        name="campaign_preview",
    ),
    path(
        "campaigns/<int:campaign_id>/send-test-email/",
        send_campaign_test_email_view,
        name="send_campaign_test_email",
    ),
    path(
        "campaigns/<int:campaign_id>/recipients/",
        campaign_recipients,
        name="campaign_recipients",
    ), 
    path(
        "campaigns/<int:campaign_id>/dry-run/",
        campaign_dry_run,
        name="campaign_dry_run",
    ),
    path(
        "campaigns/<int:campaign_id>/confirm-send/",
        campaign_confirm_send,
        name="campaign_confirm_send",
    ),
    path(
        "campaigns/<int:campaign_id>/send-real-emails/",
        campaign_send_real_emails,
        name="campaign_send_real_emails",
    ),
    path(
        "campaigns/<int:campaign_id>/retry-failed-emails/",
        campaign_retry_failed_emails,
        name="campaign_retry_failed_emails",
    ),
    path(
        "campaigns/<int:campaign_id>/schedule-status/",
        campaign_schedule_status,
        name="campaign_schedule_status",
    ),
    path(
        "campaigns/<int:campaign_id>/generate-ai-draft/",
        campaign_generate_ai_draft,
        name="campaign_generate_ai_draft",
    ),
    path(
        "campaigns/<int:campaign_id>/accept-ai-groups/",
        campaign_accept_ai_groups,
        name="campaign_accept_ai_groups",
    ),
    path(
        "campaigns/ai-create/",
        ai_campaign_create,
        name="ai_campaign_create",
    ),
    path(
        "delivery-logs/",
        delivery_logs,
        name="delivery_logs",
    ),
    path(
        "audit-logs/",
        audit_logs,
        name="audit_logs",
    ),
    path(
        "campaigns/<int:campaign_id>/",
        campaign_detail,
        name="campaign_detail",
    ),
]